#!/usr/bin/env python3
"""Regenerate agrigee_lite_client/_satellite_dates.py from the server's own
satellite registry. Run from the monorepo root whenever a satellite's date
range changes or a satellite is added/removed — then bump both packages'
version together (SPECS.md §2.1) and re-run this.

Requires `agrigee_lite` importable (e.g. the `all-features` pixi env) — this
script itself is dev tooling, not part of the published client package.

    python agrigee_lite_client/scripts/generate_satellite_dates.py > agrigee_lite_client/agrigee_lite_client/_satellite_dates.py
"""

from __future__ import annotations

from agrigee_lite.api._satellites import REGISTRY

HEADER = '''"""Static table of every satellite's temporal range (startDate/endDate).

Generated by scripts/generate_satellite_dates.py from the server's own
agrigee_lite.api._satellites.REGISTRY — do not hand-edit. Regenerate whenever
a satellite's date range changes or one is added/removed, then bump both
packages' version together (SPECS.md §2.1); test_satellite_dates_match_server
catches drift whenever agrigee_lite happens to be importable alongside this
package (i.e. in this monorepo's dev environment).

`TwoSatelliteFusion` is intentionally absent: its constructor takes two
satellite *objects*, not JSON-serializable params, so it was never reachable
through the `{name, params}` contract this table (and the REST API's
SatelliteSpec) is built around.

Sentinel2 is the only satellite whose range depends on a constructor param
(`use_sr`) rather than being fixed per class — handled explicitly in
get_satellite_date_range() below rather than complicating this table's shape
for one exception.
"""

from __future__ import annotations

from agrigee_lite_client._exceptions import AgriGEEUnknownSatelliteError

'''

FOOTER = '''

_SENTINEL2_USE_SR_FALSE = ("2016-01-01", "2050-01-01")


def get_satellite_date_range(name: str, params: dict | None = None) -> tuple[str, str]:
    """(start_date, end_date) for a satellite + params, mirroring the value
    the server's own satellite class would report for the same inputs.
    """
    if name == "Sentinel2" and params and params.get("use_sr") is False:
        return _SENTINEL2_USE_SR_FALSE

    date_range = SATELLITE_DATE_RANGES.get(name)
    if date_range is None:
        msg = (
            f"agrigee_lite_client does not know satellite {name!r}. Either it doesn't exist, or this "
            "client's version has drifted from the server's — see SPECS.md §2.1."
        )
        raise AgriGEEUnknownSatelliteError(msg)
    return date_range
'''


def main() -> None:
    entries = {}
    skipped = []
    for name, cls in sorted(REGISTRY.items()):
        try:
            instance = cls()
        except TypeError:
            skipped.append(name)
            continue
        entries[name] = (instance.startDate, instance.endDate)

    print(HEADER, end="")
    print("SATELLITE_DATE_RANGES: dict[str, tuple[str, str]] = {")
    for name, (start, end) in entries.items():
        print(f"    {name!r}: ({start!r}, {end!r}),")
    print("}")
    print(FOOTER, end="")

    import sys

    if skipped:
        print(f"# skipped (constructor needs more than defaults): {skipped}", file=sys.stderr)


if __name__ == "__main__":
    main()
