name: "Setup Python Environment"
description: "Set up Python environment with pixi"

inputs:
  pixi-version:
    description: "pixi version to use"
    required: true
    default: "latest"

runs:
  using: "composite"
  steps:
    - uses: prefix-dev/setup-pixi@v0.8.0
      with:
        pixi-version: ${{ inputs.pixi-version }}
        cache: true
