"""Static table of every satellite's temporal range (startDate/endDate).

Generated by scripts/generate_satellite_dates.py from the server's own
agrigee_lite.api._satellites.REGISTRY — do not hand-edit. Regenerate whenever
a satellite's date range changes or one is added/removed, then bump both
packages' version together (SPECS.md §2.1); test_satellite_dates_match_server
catches drift whenever agrigee_lite happens to be importable alongside this
package (i.e. in this monorepo's dev environment).

`TwoSatelliteFusion` is intentionally absent: its constructor takes two
satellite *objects*, not JSON-serializable params, so it was never reachable
through the `{name, params}` contract this table (and the REST API's
SatelliteSpec) is built around.

Sentinel2 is the only satellite whose range depends on a constructor param
(`use_sr`) rather than being fixed per class — handled explicitly in
get_satellite_date_range() below rather than complicating this table's shape
for one exception.
"""

from __future__ import annotations

from agrigee_lite_client._exceptions import AgriGEEUnknownSatelliteError

SATELLITE_DATE_RANGES: dict[str, tuple[str, str]] = {
    'AHN2Interpolated': ('1900-01-01', '2050-01-01'),
    'AHN2NonInterpolated': ('1900-01-01', '2050-01-01'),
    'AHN2Raw': ('1900-01-01', '2050-01-01'),
    'AHN3': ('1900-01-01', '2050-01-01'),
    'AHN4': ('1900-01-01', '2050-01-01'),
    'ALOSWorld3D': ('1900-01-01', '2050-01-01'),
    'ANADEM': ('1900-01-01', '2050-01-01'),
    'ASTERDEM': ('1900-01-01', '2050-01-01'),
    'ArcticDEMMosaic': ('1900-01-01', '2050-01-01'),
    'ArcticDEMStrips': ('1900-01-01', '2050-01-01'),
    'Australia5mDEM': ('1900-01-01', '2050-01-01'),
    'AustraliaDEMH': ('1900-01-01', '2050-01-01'),
    'AustraliaDEMS': ('1900-01-01', '2050-01-01'),
    'CGIARSRTM': ('1900-01-01', '2050-01-01'),
    'CanadaCDEM': ('1900-01-01', '2050-01-01'),
    'ChirpsAnnualRainfall': ('1981-01-01', '2050-01-01'),
    'CopernicusDEM': ('1900-01-01', '2050-01-01'),
    'CryoSat2Antarctica': ('1900-01-01', '2050-01-01'),
    'ETOPO1': ('1900-01-01', '2050-01-01'),
    'England1mTerrain': ('1900-01-01', '2050-01-01'),
    'FranceRGEAlti': ('1900-01-01', '2050-01-01'),
    'GLOBathy': ('1900-01-01', '2050-01-01'),
    'GMTED2010': ('1900-01-01', '2050-01-01'),
    'GTOPO30': ('1900-01-01', '2050-01-01'),
    'GreenlandGIMP': ('1900-01-01', '2050-01-01'),
    'HLSLandsat': ('2013-04-11', '2050-01-01'),
    'HLSSentinel2': ('2015-11-30', '2050-01-01'),
    'Landsat5': ('1984-03-01', '2013-05-05'),
    'Landsat7': ('1999-04-15', '2022-04-06'),
    'Landsat8': ('2013-04-11', '2050-01-01'),
    'Landsat9': ('2021-11-01', '2050-01-01'),
    'MERITDEM': ('1900-01-01', '2050-01-01'),
    'MapBiomas': ('1985-01-01', '2024-01-01'),
    'MapBiomasPastureVigor': ('2000-01-01', '2024-12-31'),
    'Modis8Days': ('2000-02-18', '2050-01-01'),
    'ModisDaily': ('2000-02-24', '2050-01-01'),
    'NAIP': ('2003-01-01', '2050-01-01'),
    'NASADEM': ('1900-01-01', '2050-01-01'),
    'NEONDEM': ('1900-01-01', '2050-01-01'),
    'PALSAR2ScanSAR': ('2014-08-04', '2050-01-01'),
    'PolarisSoilTexture': ('1900-01-01', '2050-01-01'),
    'REMAMosaic': ('1900-01-01', '2050-01-01'),
    'REMAStrips2m': ('1900-01-01', '2050-01-01'),
    'REMAStrips8m': ('1900-01-01', '2050-01-01'),
    'SRTM': ('1900-01-01', '2050-01-01'),
    'SatelliteEmbedding': ('2017-01-01', '2024-01-01'),
    'Sentinel1GRD': ('2014-10-03', '2050-01-01'),
    'Sentinel2': ('2019-01-01', '2050-01-01'),
    'USGS3DEP10m': ('1900-01-01', '2050-01-01'),
    'USGS3DEP1m': ('1900-01-01', '2050-01-01'),
    'WRBSoilClasses': ('1900-01-01', '2050-01-01'),
}


_SENTINEL2_USE_SR_FALSE = ("2016-01-01", "2050-01-01")


def get_satellite_date_range(name: str, params: dict | None = None) -> tuple[str, str]:
    """(start_date, end_date) for a satellite + params, mirroring the value
    the server's own satellite class would report for the same inputs.
    """
    if name == "Sentinel2" and params and params.get("use_sr") is False:
        return _SENTINEL2_USE_SR_FALSE

    date_range = SATELLITE_DATE_RANGES.get(name)
    if date_range is None:
        msg = (
            f"agrigee_lite_client does not know satellite {name!r}. Either it doesn't exist, or this "
            "client's version has drifted from the server's — see SPECS.md §2.1."
        )
        raise AgriGEEUnknownSatelliteError(msg)
    return date_range
